### ISSUE TITLE
Growth chart z-score lines are not correctly aligned

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#20]
See below. This dummy child's z-score is 1.2, so it should be mapped closest to the green line (which is z-score of 1), instead it is hitting the red line, which is a z-score of 2.

![screenshot_20170901-155619](https://user-images.githubusercontent.com/3488986/29973078-ea22c6be-8f36-11e7-9c5a-acaf8fd230cf.png)

**Comment by keymane** [comment]
@cagulas This issue occurs because we are using monthly z-score charts rather than daily z-score charts, so Age 2w 2d is rounded off to 0 months. We may need to change this..

Monthly Z-scores charts
For boys: http://www.who.int/childgrowth/standards/wfa_boys_0_5_zscores.txt
For girls: http://www.who.int/childgrowth/standards/wfa_girls_0_5_zscores.txt

Daily Z-scores charts
For boys: http://www.who.int/childgrowth/standards/wfa_boys_z_exp.txt
For girls: http://www.who.int/childgrowth/standards/wfa_girls_z_exp.txt

**Comment by cagulas** [comment]
Ok, this might be fine. I didn't realize the difference here. Is everything rounded off to the lower age? I.e. would a 4 week old round up to 1 month or round down to 0 months?

**Comment by keymane** [comment]
So any age less than 1 month will be rounded of to  0 months and use the z score for 0 month

**Comment by cagulas** [comment]
Ok, what about other ages? Would a 1.5 month old be rounded off to 1 month and so on?

This is probably fine. Because kids are supposed to get weighed once a month, so we should keep the system functioning for their intended workflow.

**Comment by mberg** [comment]
On the growth chart I noticed it starts with the first record for the
child. Ie) if the kid is 5 months old the chart starts at 5 months instead
of 0. I think we probabky want it to start at zero. This will
Make the charts look consistent and more like the booklet we are seeking to
replicate

**Comment by keymane** [comment]
@mberg okay, we will update the graph.
@cagulas  yes, they will be truncated unless the age is a  full number like 0, 1, 2 months..

**Comment by ekigamba** [comment]
@mberg Hi, nice to meet you.
The screen size is small and cannot accommodate a case where there a child has records more than 12 months, since we display monthly weight records on the charts

**Comment by ekigamba** [comment]
To discuss more on this with the team

**Comment by ekigamba** [comment]
Show last 9 months of child's weight

**Comment by cagulas** [comment]
Lgtm
